# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Restore Dependencies
        run: dotnet restore
          
      - name: Setup PupNet
        run: dotnet tool install -g KuiperZone.PupNet
        
      - name: Build x86 Zip
        run: pupnet -r win-x86 -y -k zip -o showcase-pdf-win-x86.zip
      
      - name: Build x64 Zip
        run: pupnet -r win-x64 -y -k zip -o showcase-pdf-win-x64.zip

      - name: Build x86 Setup
        run: pupnet -r win-x86 -y -k setup -o showcase-pdf-win-installer-x86.exe
        
      - name: Build x64 Setup
        run: pupnet -r win-x64 -y -k setup -o showcase-pdf-win-installer-x64.exe
  
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: '🎉 Showcase PDF Release'
          body: 'Latest binary releases for Showcase PDF'
          tag_name: latest
          files: |
            D:/a/showcase-pdf/showcase-pdf/Deploy/bin/showcase-pdf-win-x86.zip
            D:/a/showcase-pdf/showcase-pdf/Deploy/bin/showcase-pdf-win-x64.zip
            D:/a/showcase-pdf/showcase-pdf/Deploy/bin/showcase-pdf-win-installer-x86.exe
            D:/a/showcase-pdf/showcase-pdf/Deploy/bin/showcase-pdf-win-installer-x64.exe